### ISSUE TITLE
エントリー期間外はエントリーできないようにする

### ISSUE THREAD

**Issue by sudosanet** [lc-tut/sports-fes-entry-site2019#124]
エラーを返すなど

**Comment by hakomori64** [comment]
- 抽選エントリー開始(ゴールデンウィーク明け(2019/5/6))
- 抽選＆先着エントリー開始(大会2週間前)
- エントリー締め切り(大会1週間前)
- 大会本番(2019/5/25)
でいいですか？

**Comment by hakomori64** [comment]
つまり、現在が抽選エントリー開始より前であれば、すべてのメソッドのアクセスができない。
もしくは、現在がエントリー締め切り後であれば、GETメソッドだけ許可します。
って感じで行こうかと思います。

**Comment by hakomori64** [comment]
あ、ログインログアウトはいつでもできるようにしてあります。
