### ISSUE TITLE
publicな応募が可能かどうかを返すAPI

### ISSUE THREAD

**Issue by sudosanet** [lc-tut/sports-fes-entry-site2019#126]
先着順申込で締め切った際にフロントでも表示したいため

**Comment by hakomori64** [comment]
このAPI自体はbool値を返すだけでいいんですね？

**Comment by sudosanet** [comment]
boolでOK

**Comment by hakomori64** [comment]
- /registerableでAPIを生やします
- GETメソッドのみ受け付けます
- ?event=<競技名の英語、例えば Tennis>のように競技をパラメータとして与えてください。
- 先着順申し込み期間外、もしくはすでに登録チーム数が上限に達している場合にFalseを返します
- そうでなければTrueを返します。
